d: ch8.cpp File Reference
ch8.cpp File Reference
#include <iostream>
#include <random>
#include "Sortable_list.h"
Macros
#define CONTIGUOUS
#define SORT l.heap_sort();
Functions
void test_random (int lenL, int lenU, int num_case)
int main ()
Macro Definition Documentation
CONTIGUOUS
#define CONTIGUOUS
Definition at line 5 of file ch8.cpp.
SORT
#define SORT l.heap_sort();
Definition at line 13 of file ch8.cpp.
Function Documentation
main()
int main ()
Definition at line 103 of file ch8.cpp.
           {
   // test_static();
   test_random(10,20,7);
   // stat();
   return 0;
 }
References test_random().
test_random()
void test_random (int lenL, int lenU, int num_case)
Definition at line 35 of file ch8.cpp.
{
   uniform_int_distribution<int> lenD(lenL,lenU);
   uniform_int_distribution<int> eleD(0,99);
   default_random_engine e(time(0));
   for(int i=0;i!=num_case;++i){
     Sortable_list<int> l;
     int len=lenD(e);
     for(int j=0;j!=len;++j)
       l.insert(j,eleD(e));
     l.print();
     // INIT;
     SORT
     l.print();
     // SUM;
     cout<<endl;
   }
 }
References List< Record >::insert(), List< Record >::print(), and SORT.
Referenced by main().